server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nsv
    # TO-DO : Jasypt 라이브러리를 통한 properties 암호화
    username: postgres
    password: postgres
  sql:
    init:
      mode: always

mybatis:
  config-location: classpath:mybatis-config.xml